### PR TITLE
Navigation

### PR DESCRIPTION
**Pull request by Sameony**
Added navbar component
last pr  for today  :'D
image
image

### CODE REVIEW

**Review by krishanu2911 — APPROVED** [review]
No Changes required good to go!!

**Review by shuntzhere — APPROVED** [review]
PR Looks clean, nice use of variables throughout the stylesheet. Great Work!

**Review by vivekmehto — APPROVED** [review]
look good to me. clean code

**Review by nishasen — APPROVED** [review]
Code looks clean and good, you can merge it.

**Pull request merged**
